#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RpcMethod {
    VaultStatus,
    VaultSetup,
    VaultUnlock,
    VaultAutoUnlock,
    VaultUnlockKeychain,
    VaultLock,
    VaultKeychainStatus,
    VaultKeychainClear,
    VaultRecoverKey,
    VaultChangePassphrase,
    VaultAddRecoveryKey,
    VaultHasRecoveryKey,
    VaultReset,
    ProfileList,
    ProfileAdd,
    ProfileUpdate,
    ProfileRemove,
    ProfileTest,
    BucketsList,
    ObjectsList,
    ObjectsDelete,
    ObjectsRename,
    ObjectsStat,
    TransferUpload,
    TransferDownload,
    TransferPickAndUpload,
    TransferPickAndUploadFolder,
    TransferDownloadFolder,
    TransferCopy,
    TransferMove,
    TransferCrossBucket,
    TransferDownloadArchive,
    SyncPreview,
    SyncExecute,
    JobsList,
    JobsCancel,
    JobsClear,
    JobsGetConcurrency,
    JobsSetConcurrency,
    FavoritesLoad,
    FavoritesSave,
    ShareGenerate,
    FolderSyncListRules,
    FolderSyncAddRule,
    FolderSyncUpdateRule,
    FolderSyncRemoveRule,
    FolderSyncToggleRule,
    FolderSyncSyncNow,
    FolderSyncStartAll,
    FolderSyncStopAll,
    FolderSyncPauseAll,
    FolderSyncResumeAll,
    FolderSyncGetStatus,
    FolderSyncPreview,
    FolderSyncPickFolder,
    UpdaterCheck,
    UpdaterDownload,
    UpdaterApply,
    UpdaterLocalInfo,
}

impl RpcMethod {
    pub fn parse(value: &str) -> Option<Self> {
        match value {
            "vault:status" => Some(Self::VaultStatus),
            "vault:setup" => Some(Self::VaultSetup),
            "vault:unlock" => Some(Self::VaultUnlock),
            "vault:auto-unlock" => Some(Self::VaultAutoUnlock),
            "vault:unlock-keychain" => Some(Self::VaultUnlockKeychain),
            "vault:lock" => Some(Self::VaultLock),
            "vault:keychain-status" => Some(Self::VaultKeychainStatus),
            "vault:keychain-clear" => Some(Self::VaultKeychainClear),
            "vault:recover-key" => Some(Self::VaultRecoverKey),
            "vault:change-passphrase" => Some(Self::VaultChangePassphrase),
            "vault:add-recovery-key" => Some(Self::VaultAddRecoveryKey),
            "vault:has-recovery-key" => Some(Self::VaultHasRecoveryKey),
            "vault:reset" => Some(Self::VaultReset),
            "profile:list" => Some(Self::ProfileList),
            "profile:add" => Some(Self::ProfileAdd),
            "profile:update" => Some(Self::ProfileUpdate),
            "profile:remove" => Some(Self::ProfileRemove),
            "profile:test" => Some(Self::ProfileTest),
            "buckets:list" => Some(Self::BucketsList),
            "objects:list" => Some(Self::ObjectsList),
            "objects:delete" => Some(Self::ObjectsDelete),
            "objects:rename" => Some(Self::ObjectsRename),
            "objects:stat" => Some(Self::ObjectsStat),
            "transfer:upload" => Some(Self::TransferUpload),
            "transfer:download" => Some(Self::TransferDownload),
            "transfer:pick-and-upload" => Some(Self::TransferPickAndUpload),
            "transfer:pick-and-upload-folder" => Some(Self::TransferPickAndUploadFolder),
            "transfer:download-folder" => Some(Self::TransferDownloadFolder),
            "transfer:copy" => Some(Self::TransferCopy),
            "transfer:move" => Some(Self::TransferMove),
            "transfer:cross-bucket" => Some(Self::TransferCrossBucket),
            "transfer:download-archive" => Some(Self::TransferDownloadArchive),
            "sync:preview" => Some(Self::SyncPreview),
            "sync:execute" => Some(Self::SyncExecute),
            "jobs:list" => Some(Self::JobsList),
            "jobs:cancel" => Some(Self::JobsCancel),
            "jobs:clear" => Some(Self::JobsClear),
            "jobs:get-concurrency" => Some(Self::JobsGetConcurrency),
            "jobs:set-concurrency" => Some(Self::JobsSetConcurrency),
            "favorites:load" => Some(Self::FavoritesLoad),
            "favorites:save" => Some(Self::FavoritesSave),
            "share:generate" => Some(Self::ShareGenerate),
            "folder-sync:list-rules" => Some(Self::FolderSyncListRules),
            "folder-sync:add-rule" => Some(Self::FolderSyncAddRule),
            "folder-sync:update-rule" => Some(Self::FolderSyncUpdateRule),
            "folder-sync:remove-rule" => Some(Self::FolderSyncRemoveRule),
            "folder-sync:toggle-rule" => Some(Self::FolderSyncToggleRule),
            "folder-sync:sync-now" => Some(Self::FolderSyncSyncNow),
            "folder-sync:start-all" => Some(Self::FolderSyncStartAll),
            "folder-sync:stop-all" => Some(Self::FolderSyncStopAll),
            "folder-sync:pause-all" => Some(Self::FolderSyncPauseAll),
            "folder-sync:resume-all" => Some(Self::FolderSyncResumeAll),
            "folder-sync:get-status" => Some(Self::FolderSyncGetStatus),
            "folder-sync:preview" => Some(Self::FolderSyncPreview),
            "folder-sync:pick-folder" => Some(Self::FolderSyncPickFolder),
            "updater:check" => Some(Self::UpdaterCheck),
            "updater:download" => Some(Self::UpdaterDownload),
            "updater:apply" => Some(Self::UpdaterApply),
            "updater:local-info" => Some(Self::UpdaterLocalInfo),
            _ => None,
        }
    }
}
